In [1]:
import pandas as pd
import re

### Load the Dataset (Knowledge Base)

In [2]:
df = pd.read_parquet("../datasets/KB/acl-publication-info.74k.parquet")

### EDA to understand the dataset better

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73285 entries, 0 to 73284
Data columns (total 21 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   acl_id           73285 non-null  object
 1   abstract         73285 non-null  object
 2   full_text        73285 non-null  object
 3   corpus_paper_id  73285 non-null  int64
 4   pdf_hash         72076 non-null  object
 5   numcitedby       73285 non-null  int64
 6   url              73285 non-null  object
 7   publisher        63166 non-null  object
 8   address          66093 non-null  object
 9   year             73285 non-null  object
 10  month            65962 non-null  object
 11  booktitle        71244 non-null  object
 12  author           72619 non-null  object
 13  title            73285 non-null  object
 14  pages            59478 non-null  object
 15  doi              29678 non-null  object
 16  number           1474 non-null   object
 17  volume           1840 non-null   object
 18  journal          2037 non-null   object
 19  editor           13 non-null     object
 20  isbn             1370 non-null   object
dtypes: int64(2), object(19)
memory usage: 12.3+ MB

In [4]:
df.nunique()

acl_id             73285
abstract           63370
full_text          67379
corpus_paper_id    73284
pdf_hash           72054
numcitedby           891
url                73280
publisher            111
address              404
year                  61
month                177
booktitle           2271
author             59809
title              72510
pages              22925
doi                29676
number                 6
volume                48
journal                3
editor                 7
isbn                  37
dtype: int64

### Sort by year in Descending Order

In [5]:
df.sort_values(by='year', ascending=False, inplace=True)
df

,acl_id,abstract,full_text,corpus_paper_id,pdf_hash,numcitedby,url,publisher,address,year,...,booktitle,author,title,pages,doi,number,volume,journal,editor,isbn
18676,2022.bea-1.14,To tailor a learning system to the student's l...,To tailor a learning system to the student's l...,250390504,dc4da699b547a38e7f28ae6b39a779338b701131,0,https://aclanthology.org/2022.bea-1.14,Association for Computational Linguistics,"Seattle, Washington",2022,...,Proceedings of the 17th Workshop on Innovative...,"Loginova, Ekaterina and\nBenoit, Dries",Structural information in mathematical formula...,101--106,10.18653/v1/2022.bea-1.14,None,None,None,None,None
58886,2022.naacl-main.294,Knowledge based question answering (KBQA) is a...,Knowledge based question answering (KBQA) is a...,250390792,f2cd01324eadcacadec84cd39db4e7b8aa50714f,0,https://aclanthology.org/2022.naacl-main.294,Association for Computational Linguistics,"Seattle, United States",2022,...,Proceedings of the 2022 Conference of the Nort...,"Wang, Yu and\nV.srinivasan@samsung.com, V.sri...",A New Concept of Knowledge based Question Answ...,4007--4017,10.18653/v1/2022.naacl-main.294,None,None,None,None,None
58896,2022.naacl-main.302,Little attention has been paid on EArly Rumor ...,Little attention has been paid on EArly Rumor ...,250390604,5d2ba0b05295fc9ca45aed381fa534311c75387d,0,https://aclanthology.org/2022.naacl-main.302,Association for Computational Linguistics,"Seattle, United States",2022,...,Proceedings of the 2022 Conference of the Nort...,"Zeng, Fengzhu and\nGao, Wei",{E}arly Rumor Detection Using Neural {H}awkes ...,4105--4117,10.18653/v1/2022.naacl-main.302,None,None,None,None,None
58901,2022.naacl-main.48,Multi-triple extraction is a challenging task ...,Multi-triple extraction is a challenging task ...,250390460,b22b043e54f55d302fe3dadf840606bb27133f0a,0,https://aclanthology.org/2022.naacl-main.48,Association for Computational Linguistics,"Seattle, United States",2022,...,Proceedings of the 2022 Conference of the Nort...,"Xu, Benfeng and\nWang, Quan and\nLyu, Yajuan...",{E}m{R}el: Joint Representation of Entities an...,659--665,10.18653/v1/2022.naacl-main.48,None,None,None,None,None
58902,2022.naacl-main.304,Political perspective detection has become an ...,Political perspective detection has become an ...,248069286,823aa480c29dde65537e193ca2dadfd149199331,1,https://aclanthology.org/2022.naacl-main.304,Association for Computational Linguistics,"Seattle, United States",2022,...,Proceedings of the 2022 Conference of the Nort...,"Zhang, Wenqian and\nFeng, Shangbin and\nChen...",{KCD}: Knowledge Walks and Textual Cues Enhanc...,4129--4140,10.18653/v1/2022.naacl-main.304,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48840,1952.earlymt-1.12,,an example of a national language regularized ...,244077677,c73dd5decba81f7e4ed8b394b59273a1768ac01c,2,https://aclanthology.org/1952.earlymt-1.12,None,Massachusetts Institute of Technology,1952,...,Proceedings of the Conference on Mechanical Tr...,"Dodd, Stuart C.",Model {E}nglish for mechanical translation,None,None,None,None,None,None,None
48849,1952.earlymt-1.16,,"As I have said before, I am persuaded that we ...",244077633,75993f7e57e99231827da377498b3a4680f05a16,2,https://aclanthology.org/1952.earlymt-1.16,None,Massachusetts Institute of Technology,1952,...,Proceedings of the Conference on Mechanical Tr...,"Oswald, Victor A.",Microsemantics,None,None,None,None,None,None,None
48859,1952.earlymt-1.17,than in the procedures by which such informati...,than in the procedures by which such informati...,19613776,5c9910a11e5ee5212ecf09e122e37da10c36a47d,1,https://aclanthology.org/1952.earlymt-1.17,None,Massachusetts Institute of Technology,1952,...,Proceedings of the Conference on Mechanical Tr...,"Bull, William E.",Problems of vocabulary frequency and distribution,None,None,None,None,None,None,None
49353,1952.earlymt-1.21,,The following outline summarizes some suggesti...,34140950,b7d63112b3da746efa8ae7effb33609fd9a5e85c,15,https://aclanthology.org/1952.earlymt-1.21,None,Massachusetts Institute of Technology,1952,...,Proceedings of the Conference on Mechanical Tr...,"Booth, A. Donald and\nRichens, Richard H.",Some methods of mechanized translation,None,None,None,None,None,None,None
49306,1952.earlymt-1.3,,Conference on Mechanical Translation As annou...,244077672,b6039a7400bb3c7713429e6152e1a30d17b6fe46,2,https://aclanthology.org/1952.earlymt-1.3,None,Massachusetts Institute of Technology,1952,...,Proceedings of the Conference on Mechanical Tr...,"Bar-Hillel, Yehoshua",Conference on mechanical translation,None,None,None,None,None,None,None

In [6]:
df.drop_duplicates(inplace = True)

## Data Cleaning

### Drop some irrelevant columns (columns not needed for training RAG model)

In [7]:
df = df.drop(columns=["corpus_paper_id", "pdf_hash", "numcitedby", "publisher", "address",
    "month", "booktitle", "pages", "number", "volume", "journal", "editor", "isbn", "abstract", "doi"])
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 73285 entries, 18676 to 49306
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   acl_id     73285 non-null  object
 1   full_text  73285 non-null  object
 2   url        73285 non-null  object
 3   year       73285 non-null  object
 4   author     72619 non-null  object
 5   title      73285 non-null  object
dtypes: object(6)
memory usage: 3.9+ MB

### Renaming Columns

In [8]:
new_column_names = {
    "full_text": "text",  # Assuming full_text becomes the text column
    # "year": "publication_year",  # Example renaming year
    # "author": "authors",  # Assuming multiple authors (plural)
}

df.rename(columns=new_column_names, inplace=True)
df

,acl_id,text,url,year,author,title
18676,2022.bea-1.14,To tailor a learning system to the student's l...,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries",Structural information in mathematical formula...
58886,2022.naacl-main.294,Knowledge based question answering (KBQA) is a...,https://aclanthology.org/2022.naacl-main.294,2022,"Wang, Yu and\nV.srinivasan@samsung.com, V.sri...",A New Concept of Knowledge based Question Answ...
58896,2022.naacl-main.302,Little attention has been paid on EArly Rumor ...,https://aclanthology.org/2022.naacl-main.302,2022,"Zeng, Fengzhu and\nGao, Wei",{E}arly Rumor Detection Using Neural {H}awkes ...
58901,2022.naacl-main.48,Multi-triple extraction is a challenging task ...,https://aclanthology.org/2022.naacl-main.48,2022,"Xu, Benfeng and\nWang, Quan and\nLyu, Yajuan...",{E}m{R}el: Joint Representation of Entities an...
58902,2022.naacl-main.304,Political perspective detection has become an ...,https://aclanthology.org/2022.naacl-main.304,2022,"Zhang, Wenqian and\nFeng, Shangbin and\nChen...",{KCD}: Knowledge Walks and Textual Cues Enhanc...
...,...,...,...,...,...,...
48840,1952.earlymt-1.12,an example of a national language regularized ...,https://aclanthology.org/1952.earlymt-1.12,1952,"Dodd, Stuart C.",Model {E}nglish for mechanical translation
48849,1952.earlymt-1.16,"As I have said before, I am persuaded that we ...",https://aclanthology.org/1952.earlymt-1.16,1952,"Oswald, Victor A.",Microsemantics
48859,1952.earlymt-1.17,than in the procedures by which such informati...,https://aclanthology.org/1952.earlymt-1.17,1952,"Bull, William E.",Problems of vocabulary frequency and distribution
49353,1952.earlymt-1.21,The following outline summarizes some suggesti...,https://aclanthology.org/1952.earlymt-1.21,1952,"Booth, A. Donald and\nRichens, Richard H.",Some methods of mechanized translation
49306,1952.earlymt-1.3,Conference on Mechanical Translation As annou...,https://aclanthology.org/1952.earlymt-1.3,1952,"Bar-Hillel, Yehoshua",Conference on mechanical translation

### Text Cleaning - Cleans text data (lowercase, removes special characters)

In [9]:
def clean_text(text):
    text = text.lower()
    text = re.sub(r"[^a-zA-Z0-9\s]", "", text)  # Remove non-alphanumeric characters and spaces
    return text

# Apply cleaning to relevant columns
df["text"] = df["text"].apply(clean_text)
df["title"] = df["title"].apply(clean_text)

### Drop columns with null values now

In [10]:
df.dropna(inplace=True)
df

,acl_id,text,url,year,author,title
18676,2022.bea-1.14,to tailor a learning system to the students le...,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries",structural information in mathematical formula...
58886,2022.naacl-main.294,knowledge based question answering kbqa is a c...,https://aclanthology.org/2022.naacl-main.294,2022,"Wang, Yu and\nV.srinivasan@samsung.com, V.sri...",a new concept of knowledge based question answ...
58896,2022.naacl-main.302,little attention has been paid on early rumor ...,https://aclanthology.org/2022.naacl-main.302,2022,"Zeng, Fengzhu and\nGao, Wei",early rumor detection using neural hawkes proc...
58901,2022.naacl-main.48,multitriple extraction is a challenging task d...,https://aclanthology.org/2022.naacl-main.48,2022,"Xu, Benfeng and\nWang, Quan and\nLyu, Yajuan...",emrel joint representation of entities and emb...
58902,2022.naacl-main.304,political perspective detection has become an ...,https://aclanthology.org/2022.naacl-main.304,2022,"Zhang, Wenqian and\nFeng, Shangbin and\nChen...",kcd knowledge walks and textual cues enhanced ...
...,...,...,...,...,...,...
48840,1952.earlymt-1.12,an example of a national language regularized ...,https://aclanthology.org/1952.earlymt-1.12,1952,"Dodd, Stuart C.",model english for mechanical translation
48849,1952.earlymt-1.16,as i have said before i am persuaded that we m...,https://aclanthology.org/1952.earlymt-1.16,1952,"Oswald, Victor A.",microsemantics
48859,1952.earlymt-1.17,than in the procedures by which such informati...,https://aclanthology.org/1952.earlymt-1.17,1952,"Bull, William E.",problems of vocabulary frequency and distribution
49353,1952.earlymt-1.21,the following outline summarizes some suggesti...,https://aclanthology.org/1952.earlymt-1.21,1952,"Booth, A. Donald and\nRichens, Richard H.",some methods of mechanized translation
49306,1952.earlymt-1.3,conference on mechanical translation as annou...,https://aclanthology.org/1952.earlymt-1.3,1952,"Bar-Hillel, Yehoshua",conference on mechanical translation

In [11]:
df.to_csv("cleaned_kb_acl.csv", index=False)