In [1]:
import pandas as pd

In [2]:
acl_df = pd.read_csv('cleaned_kb_acl.csv')
acl_df

,acl_id,text,url,year,author,title
0,2022.bea-1.14,to tailor a learning system to the students le...,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries",structural information in mathematical formula...
1,2022.naacl-main.294,knowledge based question answering kbqa is a c...,https://aclanthology.org/2022.naacl-main.294,2022,"Wang, Yu and\nV.srinivasan@samsung.com, V.sri...",a new concept of knowledge based question answ...
2,2022.naacl-main.302,little attention has been paid on early rumor ...,https://aclanthology.org/2022.naacl-main.302,2022,"Zeng, Fengzhu and\nGao, Wei",early rumor detection using neural hawkes proc...
3,2022.naacl-main.48,multitriple extraction is a challenging task d...,https://aclanthology.org/2022.naacl-main.48,2022,"Xu, Benfeng and\nWang, Quan and\nLyu, Yajuan...",emrel joint representation of entities and emb...
4,2022.naacl-main.304,political perspective detection has become an ...,https://aclanthology.org/2022.naacl-main.304,2022,"Zhang, Wenqian and\nFeng, Shangbin and\nChen...",kcd knowledge walks and textual cues enhanced ...
...,...,...,...,...,...,...
72614,1952.earlymt-1.12,an example of a national language regularized ...,https://aclanthology.org/1952.earlymt-1.12,1952,"Dodd, Stuart C.",model english for mechanical translation
72615,1952.earlymt-1.16,as i have said before i am persuaded that we m...,https://aclanthology.org/1952.earlymt-1.16,1952,"Oswald, Victor A.",microsemantics
72616,1952.earlymt-1.17,than in the procedures by which such informati...,https://aclanthology.org/1952.earlymt-1.17,1952,"Bull, William E.",problems of vocabulary frequency and distribution
72617,1952.earlymt-1.21,the following outline summarizes some suggesti...,https://aclanthology.org/1952.earlymt-1.21,1952,"Booth, A. Donald and\nRichens, Richard H.",some methods of mechanized translation
72618,1952.earlymt-1.3,conference on mechanical translation as annou...,https://aclanthology.org/1952.earlymt-1.3,1952,"Bar-Hillel, Yehoshua",conference on mechanical translation

### I'm not meant to have NaN values, so I'll do some extra preprocessing here

In [3]:
acl_df.dropna(inplace=True)
acl_df

,acl_id,text,url,year,author,title
0,2022.bea-1.14,to tailor a learning system to the students le...,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries",structural information in mathematical formula...
1,2022.naacl-main.294,knowledge based question answering kbqa is a c...,https://aclanthology.org/2022.naacl-main.294,2022,"Wang, Yu and\nV.srinivasan@samsung.com, V.sri...",a new concept of knowledge based question answ...
2,2022.naacl-main.302,little attention has been paid on early rumor ...,https://aclanthology.org/2022.naacl-main.302,2022,"Zeng, Fengzhu and\nGao, Wei",early rumor detection using neural hawkes proc...
3,2022.naacl-main.48,multitriple extraction is a challenging task d...,https://aclanthology.org/2022.naacl-main.48,2022,"Xu, Benfeng and\nWang, Quan and\nLyu, Yajuan...",emrel joint representation of entities and emb...
4,2022.naacl-main.304,political perspective detection has become an ...,https://aclanthology.org/2022.naacl-main.304,2022,"Zhang, Wenqian and\nFeng, Shangbin and\nChen...",kcd knowledge walks and textual cues enhanced ...
...,...,...,...,...,...,...
72614,1952.earlymt-1.12,an example of a national language regularized ...,https://aclanthology.org/1952.earlymt-1.12,1952,"Dodd, Stuart C.",model english for mechanical translation
72615,1952.earlymt-1.16,as i have said before i am persuaded that we m...,https://aclanthology.org/1952.earlymt-1.16,1952,"Oswald, Victor A.",microsemantics
72616,1952.earlymt-1.17,than in the procedures by which such informati...,https://aclanthology.org/1952.earlymt-1.17,1952,"Bull, William E.",problems of vocabulary frequency and distribution
72617,1952.earlymt-1.21,the following outline summarizes some suggesti...,https://aclanthology.org/1952.earlymt-1.21,1952,"Booth, A. Donald and\nRichens, Richard H.",some methods of mechanized translation
72618,1952.earlymt-1.3,conference on mechanical translation as annou...,https://aclanthology.org/1952.earlymt-1.3,1952,"Bar-Hillel, Yehoshua",conference on mechanical translation

In [6]:
acl_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 66887 entries, 0 to 72618
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   acl_id  66887 non-null  object
 1   text    66887 non-null  object
 2   url     66887 non-null  object
 3   year    66887 non-null  int64
 4   author  66887 non-null  object
 5   title   66887 non-null  object
dtypes: int64(1), object(5)
memory usage: 3.6+ MB

### Put both features in lists

In [7]:
titles, texts, acl_ids, urls, years, authors = list(acl_df['title']), list(acl_df['text']), list(acl_df['acl_id']), list(acl_df['url']), list(acl_df['year']), list(acl_df['author'])

In [8]:
print(titles[20000])

select and attend towards controllable content selection in text generation

### Now, to chunk into a 100 word splits

In [9]:
print(f"Before splitting, {len(titles)} ACL Corpus articles. \n")

passage_titles = []
passages = []
passage_acl_ids = []
passage_urls = []
passage_years = []
passage_authors = []

# For each text and its title...
for i in range(len(titles)):

    title = titles[i]
    text = texts[i]
    acl_id = acl_ids[i]
    url = urls[i]
    year = years[i]
    author = authors[i]

    # Skip over any without contents
    if len(text) == 0:
        print("Skipping empty text:", text)
        continue

    # Split text on whitespace
    words = text.split()

    # Loop over the words, incrementing by 100
    for i in range(0, len(words), 100):

        # Select the next 100 words
        chunk_words = words[i : i + 100]

        # Recombine thw ords into a passage by joining with whitespace
        chunk = " ".join(chunk_words)

        # Remove any trailinig whitespace
        chunk = chunk.strip()

        # To avoid possible edge cases, skip any empty chunks.
        if len(chunk) == 0:
            continue

        # Store each passage chunk for each title
        passage_titles.append(title)
        passages.append(chunk)
        passage_acl_ids.append(acl_id)
        passage_urls.append(url)
        passage_years.append(year)
        passage_authors.append(author)

print(' Done.\n')

chunked_corpus = {'title': passage_titles, 'text': passages, 'acl_id': passage_acl_ids, 'url': passage_urls, 'year': passage_years, 'author': passage_authors}

print(f"After splitting, {len(chunked_corpus['title'])} '100-word chunk' passages.")

Before splitting, 66887 ACL Corpus articles.

 Done.

After splitting, 2423290 '100-word chunk' passages.

### Save the chunked corpus to disk

In [10]:
chunked_df = pd.DataFrame(chunked_corpus)

chunked_df

,title,text,acl_id,url,year,author
0,structural information in mathematical formula...,to tailor a learning system to the students le...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
1,structural information in mathematical formula...,2010 a key component of a personalised system ...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
2,structural information in mathematical formula...,educational context is still understudied this...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
3,structural information in mathematical formula...,is a mathematical term such a representation a...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
4,structural information in mathematical formula...,of mathematical symbols a possible extension i...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
...,...,...,...,...,...,...
2423285,some methods of mechanized translation,so far as the second machine treatment is conc...,1952.earlymt-1.21,https://aclanthology.org/1952.earlymt-1.21,1952,"Booth, A. Donald and\nRichens, Richard H."
2423286,some methods of mechanized translation,initial letter group storage technique outline...,1952.earlymt-1.21,https://aclanthology.org/1952.earlymt-1.21,1952,"Booth, A. Donald and\nRichens, Richard H."
2423287,conference on mechanical translation,conference on mechanical translation as announ...,1952.earlymt-1.3,https://aclanthology.org/1952.earlymt-1.3,1952,"Bar-Hillel, Yehoshua"
2423288,conference on mechanical translation,drive in a private dining room at 630 pm the o...,1952.earlymt-1.3,https://aclanthology.org/1952.earlymt-1.3,1952,"Bar-Hillel, Yehoshua"
2423289,conference on mechanical translation,will be made at the wednesday morning session ...,1952.earlymt-1.3,https://aclanthology.org/1952.earlymt-1.3,1952,"Bar-Hillel, Yehoshua"

In [11]:
chunked_df.to_csv("chunked_kb_acl.csv", index=False)

#### 67454 articles == 2 million plus passages is taking too long to run

### Create a smaller subset containing 2973 articles == 100k passages

In [12]:
sub_chunked_df = chunked_df[:100000]

In [13]:
sub_chunked_df

,title,text,acl_id,url,year,author
0,structural information in mathematical formula...,to tailor a learning system to the students le...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
1,structural information in mathematical formula...,2010 a key component of a personalised system ...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
2,structural information in mathematical formula...,educational context is still understudied this...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
3,structural information in mathematical formula...,is a mathematical term such a representation a...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
4,structural information in mathematical formula...,of mathematical symbols a possible extension i...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
...,...,...,...,...,...,...
99995,is attention explanation an introduction to th...,measures evaluation methodology for explanatio...,2022.acl-long.269,https://aclanthology.org/2022.acl-long.269,2022,"Bibal, Adrien and\nCardon, R{\'e}mi and\nAlf..."
99996,is attention explanation an introduction to th...,first point neely et al 2021 compare explanati...,2022.acl-long.269,https://aclanthology.org/2022.acl-long.269,2022,"Bibal, Adrien and\nCardon, R{\'e}mi and\nAlf..."
99997,is attention explanation an introduction to th...,al 2021 propose a general discussion about log...,2022.acl-long.269,https://aclanthology.org/2022.acl-long.269,2022,"Bibal, Adrien and\nCardon, R{\'e}mi and\nAlf..."
99998,is attention explanation an introduction to th...,ddp to evaluate explanations based on the defi...,2022.acl-long.269,https://aclanthology.org/2022.acl-long.269,2022,"Bibal, Adrien and\nCardon, R{\'e}mi and\nAlf..."
99999,is attention explanation an introduction to th...,and pinter 2019 is the underlying assumptions ...,2022.acl-long.269,https://aclanthology.org/2022.acl-long.269,2022,"Bibal, Adrien and\nCardon, R{\'e}mi and\nAlf..."

In [14]:
sub_chunked_df['title'].nunique()

2305

In [15]:
sub_chunked_df.to_csv("sub_chunk_kb_acl-100k.csv", index=False)

### n articles == 200k passages

In [16]:
sub_chunked_df = chunked_df[:200000]

In [17]:
sub_chunked_df

,title,text,acl_id,url,year,author
0,structural information in mathematical formula...,to tailor a learning system to the students le...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
1,structural information in mathematical formula...,2010 a key component of a personalised system ...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
2,structural information in mathematical formula...,educational context is still understudied this...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
3,structural information in mathematical formula...,is a mathematical term such a representation a...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
4,structural information in mathematical formula...,of mathematical symbols a possible extension i...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
...,...,...,...,...,...,...
199995,gulu at semeval2021 task 7 detecting and ratin...,09190 but 1c scores 05561 from the distributio...,2021.semeval-1.156,https://aclanthology.org/2021.semeval-1.156,2021,"Yang, Maoqin"
199996,gulu at semeval2021 task 7 detecting and ratin...,it is almost impossible to identify humor by e...,2021.semeval-1.156,https://aclanthology.org/2021.semeval-1.156,2021,"Yang, Maoqin"
199997,synchronous dual network with crosstype attent...,joint entity and relation extraction is challe...,2021.emnlp-main.219,https://aclanthology.org/2021.emnlp-main.219,2021,"Wu, Hui and\nShi, Xiaodong"
199998,synchronous dual network with crosstype attent...,the other hand sdn explicitly models the inter...,2021.emnlp-main.219,https://aclanthology.org/2021.emnlp-main.219,2021,"Wu, Hui and\nShi, Xiaodong"
199999,synchronous dual network with crosstype attent...,subtasks named entity recognition ner and rela...,2021.emnlp-main.219,https://aclanthology.org/2021.emnlp-main.219,2021,"Wu, Hui and\nShi, Xiaodong"

In [18]:
sub_chunked_df['title'].nunique()

4711

In [19]:
sub_chunked_df.to_csv("sub_chunk_kb_acl-200k.csv", index=False)

### n articles == 500k passages

In [20]:
sub_chunked_df = chunked_df[:500000]

In [21]:
sub_chunked_df

,title,text,acl_id,url,year,author
0,structural information in mathematical formula...,to tailor a learning system to the students le...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
1,structural information in mathematical formula...,2010 a key component of a personalised system ...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
2,structural information in mathematical formula...,educational context is still understudied this...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
3,structural information in mathematical formula...,is a mathematical term such a representation a...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
4,structural information in mathematical formula...,of mathematical symbols a possible extension i...,2022.bea-1.14,https://aclanthology.org/2022.bea-1.14,2022,"Loginova, Ekaterina and\nBenoit, Dries"
...,...,...,...,...,...,...
499995,interactivelypropagative attention learning fo...,variety of advanced techniques have been devel...,2020.coling-main.282,https://aclanthology.org/2020.coling-main.282,2020,"Ruan, Huibin and\nHong, Yu and\nXu, Yang an..."
499996,interactivelypropagative attention learning fo...,basic ones like cnn rnn and lstm zhang et al 2...,2020.coling-main.282,https://aclanthology.org/2020.coling-main.282,2020,"Ruan, Huibin and\nHong, Yu and\nXu, Yang an..."
499997,interactivelypropagative attention learning fo...,area table 4 shows the performance of the prev...,2020.coling-main.282,https://aclanthology.org/2020.coling-main.282,2020,"Ruan, Huibin and\nHong, Yu and\nXu, Yang an..."
499998,interactivelypropagative attention learning fo...,the best performance for the contingent con an...,2020.coling-main.282,https://aclanthology.org/2020.coling-main.282,2020,"Ruan, Huibin and\nHong, Yu and\nXu, Yang an..."
499999,interactivelypropagative attention learning fo...,able to identify as many attentionworthy words...,2020.coling-main.282,https://aclanthology.org/2020.coling-main.282,2020,"Ruan, Huibin and\nHong, Yu and\nXu, Yang an..."

In [22]:
sub_chunked_df['title'].nunique()

12041

In [23]:
sub_chunked_df.to_csv("sub_chunk_kb_acl-500k.csv", index=False)